project_id = "afrcagkprhtvvucukubf"

[functions.register-event]
verify_jwt = false

[functions.send-download-email]
verify_jwt = false

[functions.generate-og-image]
verify_jwt = true

[functions.translate-content]
verify_jwt = true

[functions.cleanup-orphaned-images]
verify_jwt = true

[functions.get-logo-base64]
verify_jwt = false
